---
- hosts: all
  become: true
  roles:
  - basic

- hosts: server1
  become: true
  vars:
    NODEJS_VERSION: "12"
    ansible_distribution_release: "bionic"
    app_path: "/var/www"
    app: "example"
    ssl_key_path: "/etc/ssl"
    ssl_key_name: "main"
  roles:
  - node
  - example