- name: Adding node repository
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ NODEJS_VERSION }}.x {{ ansible_distribution_release }} main"
    state: present
    update_cache: yes
  notify:
  - add-gpg-key-for-node

- name: Install the nodejs
  apt:
    name: nodejs
    state: present